-- Benim Finans V6.0 Supabase schema
-- Supabase > SQL Editor > New query içine yapıştırıp Run deyin.

create table if not exists public.assets (
  id bigint generated by default as identity primary key,
  name text not null,
  symbol text not null unique,
  category text not null,
  currency text default 'TRY',
  manual_price_try double precision default 0,
  active boolean default true,
  archived boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  tx_date date not null,
  asset_symbol text not null,
  action text not null,
  quantity double precision not null default 0,
  price_try double precision not null default 0,
  commission_try double precision default 0,
  note text default '',
  created_at timestamptz default now()
);

create table if not exists public.price_cache (
  symbol text primary key,
  price_try double precision default 0,
  source text default '',
  updated_at timestamptz default now()
);

-- Tek kullanıcı kişisel uygulama için RLS kapalı bırakılabilir.
-- Repo public ise service_role anahtarı KULLANMAYIN; sadece anon public key'i Streamlit Secrets'a ekleyin.
alter table public.assets disable row level security;
alter table public.transactions disable row level security;
alter table public.price_cache disable row level security;
